### ISSUE TITLE
handle optical devices same way as disks when ignoring devices

### ISSUE THREAD

**Issue by rvykydal** [storaged-project/blivet#779]
MOTIVATION: handle https://github.com/storaged-project/blivet/pull/777 in better, more generic way.

Currently ignoring devices (hiding in devicetree) is applied only to DiskDevices, not to OpticalDevices.

This results in some problems, for example in installations into image in running system, which should protect all devices except image devices, cdrom is not protected which means it is torn down / unmounted (https://github.com/storaged-project/blivet/pull/777) during storage reset and device tree population. It is caused by hiding only DiskDevices - which don't include OpticalDevices. It seems that OpticalDevices should be treated same as DiskDevices in this context:
1) hiding ignored disks would become hidning of ignored devices:
https://github.com/rvykydal/blivet/blob/ignore-and-hide-also-optical-devices/blivet/devicetree.py#L922
where the class of devices including optical devices would be used, meaning:
```
for disk in [d for d in self._devices if d.is_disk or d.type == "cdrom"]:
```
Another example could be
2) marking of read-only devices:
https://github.com/rvykydal/blivet/blob/ignore-and-hide-also-optical-devices/blivet/populator/populator.py#L209
where only DiskDevices are marked.

**Comment by poncovka** [comment]
I think that there is a difference between hidden and protected devices. Hidden devices are not visible in the device tree, so we treat them as nonexistent. Protected devices are visible in the device tree, so we can do some limited actions with them. I am afraid, that it is not possible to use a hidden cdrom device as an installation source (with the current code).

The problem is that we are not able to mark devices as protected before the teardown in the `populate` method: https://github.com/storaged-project/blivet/blob/3.1-devel/blivet/populator/populator.py#L420

I see two possible solutions. The teardown could be removed from the `populate` method and called in Anaconda after we mark the devices as protected: https://github.com/rhinstaller/anaconda/blob/master/pyanaconda/storage/osinstall.py#L238

Or Anaconda could provide a list of protected devices that can be applied in the `populate` method in a way similar to the ignored disks.

**Comment by dwlehman** [comment]
> I see two possible solutions. The teardown could be removed from the `populate` method and called in Anaconda after we mark the devices as protected: https://github.com/rhinstaller/anaconda/blob/master/pyanaconda/storage/osinstall.py#L238
> 
> Or Anaconda could provide a list of protected devices that can be applied in the `populate` method in a way similar to the ignored disks.

I prefer either of these approaches to the new flag approach or this approach. The first is the best IMO since we only do `teardown_all` at the end of `populate` when anaconda is driving. Blivet normally doesn't do that. So just removing it has no effect on blivet's normal operation and also solves your current problem with the installation media.

**Comment by poncovka** [comment]
The call of `teardown_all` was removed from `populate` in the pull request https://github.com/storaged-project/blivet/pull/780. So Anaconda should be able to protect cdroms without further changes in Blivet.

**Comment by dwlehman** [comment]
Excellent! Thanks!
